letters = [chr(i) for i in range(65, 91)] + [chr(i) for i in range(97, 123)]
digits = [chr(i) for i in range(48, 58)]
symbol = [';', ':', ',', '[', ']', '(', ')', '{', '}', '+', '-', '<']
equal_symbol = ['=']
slash_symbol = ['/']
star_symbol = ['*']
all_symbols = symbol + equal_symbol + slash_symbol + star_symbol
new_line = ['\n']
whitespace = [' ', '\n', '\r', '\t', '\v', '\f']
keywords = ['break', 'else', 'if', 'int', 'while', 'return', 'void', 'default', 'main']
valid_chars = letters + digits + all_symbols + whitespace + ['']
