start_nonterminal = "Program"

actioned_grammar = { # currently doesn't support action at the very beginning. tell me if you need it Emad jan
    "Program": [["DeclarationList", '$']],
    "DeclarationList": [["Declaration", "DeclarationList"], []],
    "Declaration": [["DeclarationInitial", "DeclarationPrime"]],
    "DeclarationInitial": [["TypeSpecifier", "ID"]],
    "DeclarationPrime": [["FunDeclarationPrime"], ["VarDeclarationPrime"]],
    "VarDeclarationPrime": [[";"], ["[", "NUM", "]", ";"]],
    "FunDeclarationPrime": [["(", "Params", ")", "CompoundStmt"]],
    "TypeSpecifier": [["int"], ["void"]],
    "Params": [["int", "ID", "ParamPrime", "ParamList"], ["void"]],
    "ParamList": [[",", "Param", "ParamList"], []],
    "Param": [["DeclarationInitial", "ParamPrime"]],
    "ParamPrime": [["[", "]"], []],
    "CompoundStmt": [["{", "DeclarationList", "StatementList", "}"]],
    "StatementList": [["Statement", "StatementList"], []],
    "Statement": [["ExpressionStmt"], ["CompoundStmt"], ["SelectionStmt"], ["IterationStmt"], ["ReturnStmt"]],
    "ExpressionStmt": [["Expression", ";"], ["break", ";"], [";"]],
    "SelectionStmt": [["if", "(", "Expression", ")", "Statement", "else", "Statement"]],
    "IterationStmt": [["while", "(", "Expression", ")", "Statement"]],
    "ReturnStmt": [["return", "ReturnStmtPrime"]],
    "ReturnStmtPrime": [[";"], ["Expression", ";"]],

    "Expression": [["SimpleExpressionZegond"], ["ID","#PID", "B"]],
    "B": [["=", "Expression", "#ASSIGN"], ["[", "Expression", "]", "LIST_ACC", "H"], ["SimpleExpressionPrime"]],
    "H": [["=", "Expression", "#ASSIGN"], ["G", "D", "C"]],
    "SimpleExpressionZegond": [["AdditiveExpressionZegond", "C"]],
    "SimpleExpressionPrime": [["AdditiveExpressionPrime", "C"]],
    "C": [["Relop", "#SYMB", "AdditiveExpression", "#COMPARE"], []],
    "Relop": [["<"], ["=="]],
    "AdditiveExpression": [["Term", "D"]],
    "AdditiveExpressionPrime": [["TermPrime", "D"]],
    "AdditiveExpressionZegond": [["TermZegond", "D"]],
    "D": [["Addop", "#SYMB", "Term", "#OPERATE","D"], []],
    "Addop": [["+"], ["-"]],
    "Term": [["SignedFactor", "G"]],
    "TermPrime": [["SignedFactorPrime", "G"]],
    "TermZegond": [["SignedFactorZegond", "G"]],
    "G": [["*", "#SYMB", "SignedFactor", "#OPERATE", "G"], []],
    "SignedFactor": [["+", "Factor"], ["-", "Factor", "#NEG"], ["Factor"]],
    "SignedFactorPrime": [["FactorPrime"]],
    "SignedFactorZegond": [["+", "Factor"], ["-", "Factor", "#NEG"], ["FactorZegond"]],
    "Factor": [["(", "Expression", ")"], ["ID", "#PID", "VarCallPrime"], ["NUM","#IMM"]],
    "VarCallPrime": [["(", "Args", ")"], ["VarPrime"]],
    "VarPrime": [["[", "Expression", "]", "#LIST_ACC"], []],
    "FactorPrime": [["(", "Args", ")"], []],
    "FactorZegond": [["(", "Expression", ")"], ["NUM", "#IMM"]],
    "Args": [["ArgList"], []],
    "ArgList": [["Expression", "ArgListPrime"]],
    "ArgListPrime": [[",", "Expression", "ArgListPrime"], []],
}

EPS = ""